export const ATTEMPTING_LOGIN = "ATTEMPTING_LOGIN"
export const ATTEMPT_LOGIN_SUCCESS = "ATTEMPT_LOGIN_SUCCESS"
export const ATTEMPT_LOGIN_FAILED = "ATTEMPT_LOGIN_FAILED"

export const ATTEMPTING_LOGOUT = "ATTEMPTING_LOGOUT"
export const ATTEMPT_LOGOUT_SUCCESS = "ATTEMPT_LOGOUT_SUCCESS"
export const ATTEMPT_LOGOUT_FAILED = "ATTEMPT_LOGOUT_FAILED"
