export const ATTEMPTING_GET_CURRENT_USER = "ATTEMPTING_GET_CURRENT_USER"
export const ATTEMPT_GET_CURRENT_USER_SUCCESS = "ATTEMPT_GET_CURRENT_USER_SUCCESS"
export const ATTEMPT_GET_CURRENT_USER_FAILED = "ATTEMPT_GET_CURRENT_USER_FAILED"

export const ATTEMPTING_LOGIN = "ATTEMPTING_LOGIN"
export const ATTEMPT_LOGIN_SUCCESS = "ATTEMPT_LOGIN_SUCCESS"
export const ATTEMPT_LOGIN_FAILED = "ATTEMPT_LOGIN_FAILED"

export const ATTEMPTING_LOGOUT = "ATTEMPTING_LOGOUT"
export const ATTEMPT_LOGOUT_SUCCESS = "ATTEMPT_LOGOUT_SUCCESS"
export const ATTEMPT_LOGOUT_FAILED = "ATTEMPT_LOGOUT_FAILED"

export const ATTEMPTING_SIGN_UP = "ATTEMPTING_SIGN_UP"
export const ATTEMPT_SIGN_UP_SUCCESS = "ATTEMPT_SIGN_UP_SUCCESS"
export const ATTEMPT_SIGN_UP_FAILED = "ATTEMPT_SIGN_UP_FAILED"

export const ATTEMPTING_FETCH_RECRUITERS = "ATTEMPTING_FETCH_RECRUITERS"
export const ATTEMPT_FETCH_RECRUITERS_SUCCESS = "ATTEMPT_FETCH_RECRUITERS_SUCCESS"
export const ATTEMPT_FETCH_RECRUITERS_FAILED = "ATTEMPT_FETCH_RECRUITERS_FAILED"