export const SET_OPTIONS = "SET_OPTIONS";

export const FETCH_APPLICATIONS= "FETCH_APPLICATIONS"
export const FETCHING_APPLICATIONS = "FETCHING_APPLICATIONS"
export const FETCH_APPLICATIONS_FAILED = "FETCH_APPLICATIONS_FAILED"
export const VIEW_APPLICATIONS = "VIEW_APPLICATIONS"