export const FETCHING_APPLICATIONS = "FETCHING_APPLICATIONS"
export const FETCH_APPLICATIONS_SUCCESS = "FETCH_APPLICATIONS_SUCCESS"
export const FETCH_APPLICATIONS_FAILED = "FETCH_APPLICATIONS_FAILED"

export const SET_APPLICATIONS_FILTER_OPTIONS = "SET_APPLICATIONS_FILTER_OPTIONS"
export const SET_TABLE_FILTER_OPTIONS = "SET_TABLE_FILTER_OPTIONS"
export const SET_APPLICATIONS_SORT_OPTIONS = "SET_APPLICATIONS_SORT_OPTIONS"
export const SET_CURRENT_APPLICATION  = "SET_CURRENT_APPLICATION"

export const UPDATE_RECRUITER_NOTES  = "UPDATE_RECRUITER_NOTES"
export const ADD_PAIRING = "ADD_PAIRING"
export const ADD_TO_TALENT_POOL = "ADD_TO_TALENT_POOL"

export const SET_SHOWING_MODAL = "SET_SHOWING_MODAL"
