export const FETCHING_APPLICATIONS = "FETCHING_APPLICATIONS"
export const FETCH_APPLICATIONS_SUCCESS = "FETCH_APPLICATIONS_SUCCESS"
export const FETCH_APPLICATIONS_FAILED = "FETCH_APPLICATIONS_FAILED"

export const SET_APPLICATIONS_FILTER_OPTIONS = "SET_APPLICATIONS_FILTER_OPTIONS"
export const SET_TABLE_FILTER_OPTIONS = "SET_TABLE_FILTER_OPTIONS"
export const SET_APPLICATIONS_SORT_OPTIONS = "SET_APPLICATIONS_SORT_OPTIONS"
export const SET_CURRENT_APPLICATION  = "SET_CURRENT_APPLICATION"

export const SET_WERE_CHANGES = "SET_WERE_CHANGES"

export const ADD_PAIRING = "ADD_PAIRING"
export const ADD_TO_TALENT_POOL = "ADD_TO_TALENT_POOL"

export const SET_SHOWING_MODAL = "SET_SHOWING_MODAL"
export const SUBMITTING_NOTES = "SUBMITING_NOTES"
export const SUBMIT_NOTES_SUCCESS = "SUBMIT_NOTES_SUCCESS"
export const SUBMIT_NOTES_FAILED = "SUBMIT_NOTES_FAILED"
